# theme: jekyll-theme-midnight
remote_theme: higgsbosoncodes/forty-jekyll-theme

# site settings
title: Forty
subtitle: by HTML5 UP
email: beimgraben8@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Frederik Beimgraben
street_address: Muehleweg 13
city: Eningen unter Achalm
state: BW
zip_code: 72800
country: Germany

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sfz-eningen

# build settings
markdown: kramdown

sass:
  style: compressed
